name: dynamiclist
description: A new Flutter project for Android Team Task Round.
publish_to: 'none' # Remove this line if you wish to publish to
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Yanone
      fonts:
        - asset: fonts/YanoneKaffeesatz-VariableFont_wght.ttf
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
        - asset: fonts/DancingScript-Bold.ttf
        - asset: fonts/DancingScript-Medium.ttf
        - asset: fonts/DancingScript-SemiBold.ttf

  assets:
    - fonts/
